browniebroke/django-codemod

django_codemod/codemods/django_40.py
tests/codemods/test_django_40.py

If a file has other kind of imports, the codemad crashes with:
```
ValueError: not enough values to unpack (expected 3, got 0)
```

Fix ForceTextToStrCommand when other imports are present in the file

---

README.rst
django_codemod/commands/django_40.py
docs/usage.md
tests/commands/test_django_40.py

Rename `ForceTextToStrCommand` to `ForceTextToForceStrCommand` and `SmartTextToStrCommand` to `SmartTextToSmartStrCommand`.

Rename commands to reflect the functions they work with

---

setup.cfg
setup.py

Move metadata from `setup.py` to `setup.cfg` as per [this documentation](https://setuptools.readthedocs.io/en/latest/setuptools.html#configuring-setup-using-setup-cfg-files).

Migrate package metadata to declarative syntax

---

docs/usage.md

Document how to list all available codemodders

---

django_codemod/commands/base.py
django_codemod/commands/django_30.py
django_codemod/commands/django_40.py

- Replace `old_name` and `new_name` by `rename_from` and `rename_to` with full import path
- Generate the import from matcher based on the `rename_from` attribute
- Replace custom logic to insert new import by `AddImportsVisitor`
- Hook to easily update `Call` arguments

Refactor BaseSimpleFuncRename to simplify implementing new codemod

---

django_codemod/visitors/base.py
tests/commands/test_django_40.py

It's quite common to import ugettext as `_` like this:
```
from django.utils.translation import ugettext as _
translated = = _("content")
```
In such case, the `_` alis is lost which causes invalid syntax.

Fix bug with lost alias when 'import as' is used

---

django_codemod/commands/django_codemod.py
django_codemod/visitors/django_30.py
docs/codemods.rst
tests/visitors/test_django_30.py

From [Django 3.0 deprecations](https://docs.djangoproject.com/en/dev/internals/deprecation/#deprecation-removed-in-3-0):
> The shim to allow InlineModelAdmin.has_add_permission() to be defined without an obj argument will be removed.

Add the `obj` argument to `InlineModelAdmin.has_add_permission()`

---

tests/visitors/test_base.py
tests/visitors/test_django_30.py
tests/visitors/test_django_40.py

Lots of the visitors tests actually are testing functionality from the base class, and they are duplicated all over.
This tests all the edge cases using the base class and reduce visitor tests to more minimal version.

Move duplicated visitors tests for base class

---

django_codemod/commands/django_codemod.py
django_codemod/visitors/__init__.py
django_codemod/visitors/http.py
docs/codemods.rst
tests/visitors/test_http.py

From [Django 3.0 release notes](https://docs.djangoproject.com/en/dev/releases/3.0/#deprecated-features-3-0):
> `django.utils.http.urlquote()`, `urlquote_plus()`, `urlunquote()`, and `urlunquote_plus()` are deprecated in favor of the functions that they’re aliases for: `urllib.parse.quote()`, `quote_plus()`, `unquote()`, and `unquote_plus()`.

Resolve deprecations from `django.utils.http` in Django 3.0

---

django_codemod/commands/django_codemod.py
django_codemod/visitors/__init__.py
django_codemod/visitors/html.py
docs/codemods.rst
tests/visitors/test_html.py

From [Django 3.0 release notes](https://docs.djangoproject.com/en/dev/releases/3.0/#deprecated-features-3-0):
> `django.utils.text.unescape_entities()` is deprecated in favor of `html.unescape()`. Note that unlike `unescape_entities()`, `html.unescape()` evaluates lazy strings immediately.

Resolve deprecation of `django.utils.text.unescape_entities` in Django 3.0

---

django_codemod/visitors/__init__.py
django_codemod/visitors/encoding.py
django_codemod/visitors/lru_cache.py
django_codemod/visitors/os_utils.py
docs/codemods.rst
tests/test_cli.py
tests/visitors/test_encoding.py
tests/visitors/test_lru_cache.py
tests/visitors/test_os_utils.py

- `django.utils.lru_cache.lru_cache()` - `Alias of functools.lru_cache()`.
- `django.utils._os.abspathu()` - Alias of `os.path.abspath()`.
- `django.utils.encoding.python_2_unicode_compatible()` - Alias of `six.python_2_unicode_compatible()`.

Resolve some removed private Python 2 compatibility APIs

---

django_codemod/visitors/__init__.py
django_codemod/visitors/base.py
django_codemod/visitors/decorators.py
docs/codemods.rst
tests/test_cli.py
tests/visitors/test_decorators.py

As per [Django 3.0 release notes](https://docs.djangoproject.com/en/dev/releases/3.0/#removed-private-python-2-compatibility-apis):
> `django.utils.decorators.ContextDecorator` - Alias of `contextlib.ContextDecorator`.

Resolve deprecation of `django.utils.decorators.ContextDecorator` in Django 2.0

---

django_codemod/visitors/__init__.py
django_codemod/visitors/decorators.py
docs/codemods.rst
tests/test_cli.py
tests/visitors/test_decorators.py

One of the Python 2 compatibility API, from [Django 3.0 release notes](https://docs.djangoproject.com/en/dev/releases/3.0/#removed-private-python-2-compatibility-apis):
> `django.utils.decorators.available_attrs()` - This function returns `functools.WRAPPER_ASSIGNMENTS`.

Resolve deprecation of `django.utils.decorators.available_attrs` in Django 2.0

---

django_codemod/visitors/__init__.py
django_codemod/visitors/models.py
tests/test_cli.py
tests/visitors/test_models.py

Adding a feature to handle adding the `on_delete` argument to `ForeignKey` and `OneToOneField` types: https://docs.djangoproject.com/en/dev/releases/1.9/#foreignkey-and-onetoonefield-on-delete-argument
TODO:
Stretch:

Add support for adding `on_delete` for `ForeignKey` and `OneToOneField`

---

django_codemod/cli.py

Fix bug with CLI processing entire filesystem

---

django_codemod/cli.py
django_codemod/commands.py
tests/test_cli.py
tests/visitors/base.py

This change enables us to test the CLI without patching our own function, to have a test running the whole code path.

Internal refactoring of CLI and test improvements

---

.github/workflows/lint.yml
README.md
django_codemod/cli.py
django_codemod/visitors/admin.py
django_codemod/visitors/base.py
django_codemod/visitors/core.py
django_codemod/visitors/decorators.py
django_codemod/visitors/encoding.py
django_codemod/visitors/html.py
django_codemod/visitors/http.py
django_codemod/visitors/lru_cache.py
django_codemod/visitors/models.py
django_codemod/visitors/os_utils.py
django_codemod/visitors/shortcuts.py
django_codemod/visitors/translations.py
django_codemod/visitors/urls.py
docs/codemods.md
docs/usage.md
setup.cfg
tests/test_cli.py

Codemodders are listed as a table using the rich package
Fixes #75

Add CLI command to list all codemodders

---

django_codemod/visitors/__init__.py
django_codemod/visitors/timezone.py
tests/test_cli.py
tests/visitors/test_timezone.py

> `django.utils.timezone.FixedOffset` is deprecated in favor of `datetime.timezone`

New visitor to replace `timezone.FixedOffset` by `datetime.timezone`

---

django_codemod/visitors/__init__.py
django_codemod/visitors/paginator.py
docs/codemods.md
tests/test_cli.py
tests/visitors/test_paginator.py

From Django 2.2 release notes:
> The undocumented `QuerySetPaginator` alias of `django.core.paginator.Paginator` is deprecated
This is removed in Django 3.1

New visitor to replace usages of `QuerySetPaginator`

---

django_codemod/visitors/__init__.py
django_codemod/visitors/postgres_fields.py
docs/codemods.md
tests/test_cli.py
tests/visitors/test_postgres_fields.py

From Django 2.2 release notes:
> The `FloatRangeField` model and form fields in `django.contrib.postgres` are deprecated in favor of a new name, `DecimalRangeField`, to match the underlying `numrange` data type used in the database.
This is removed in Django 3.1

Add visitor to replace usages of postgres' `FloatRangeFormField`

---

django_codemod/visitors/__init__.py
django_codemod/visitors/base.py
django_codemod/visitors/template_tags.py
docs/codemods.md
tests/test_cli.py
tests/visitors/test_base.py
tests/visitors/test_template_tags.py

Deprecated in Django 1.9:
> Tags that use `assignment_tag` should be updated
> to use `simple_tag`.
Fixes #121

Add a transformer for replacing `assignment_tag` by `simple_tag`

---

django_codemod/visitors/__init__.py
django_codemod/visitors/signals.py
docs/codemods.md
tests/test_cli.py
tests/visitors/test_signals.py

Remove the `weak` argument from `Signal.disconnect()`

---

django_codemod/cli.py
tests/test_cli.py

As it says on the tin: support e.g.
```
djcodemod run --deprecated-in 3.0 package1 package2
```
or if you're even wilder, e.g.
```
git ls-files | grep 'py$' | grep -v migrations | xargs djcodemod run --deprecated-in 3.0
```

feat: support multiple target path arguments

---

django_codemod/cli.py
docs/usage.md
tests/test_cli.py

<del>I'm not sure if this is a bit controversial since the original explicitly only allowed either option, but I don't see harm in a "just bring me up to date fam" option (speaking of which, `--all` could be added separately).</del>
* makes `--removed-in` and `--deprecated-in` repeatable
* allows mixing and matching the two
<del>* adds an `--all` option</del>

Allow both removed-in and deprecated-in

---

django_codemod/utils/calls.py
django_codemod/visitors/__init__.py
django_codemod/visitors/base.py
django_codemod/visitors/crypto.py
django_codemod/visitors/models.py
tests/visitors/test_crypto.py

Not passing a length to `get_random_string()` is deprecated in Django 3.1

Add codemod to add a length parameter to get_random_string()

---

django_codemod/cli.py
tests/test_cli.py

Fixes #207. 
```
$ djcodemod run --help
Usage: djcodemod run [OPTIONS] PATH...
Automatically fixes deprecations removed Django deprecations.
This command takes the path to target as argument and a version of Django
to select code modifications to apply.
Options:
--removed-in VERSION            The version of Django where feature are
removed.
--deprecated-in VERSION         The version of Django where deprecations
started.
--codemod (see `djcodemod list`)
Choose a specific codemod to run. Can be
repeated.
--help                          Show this message and exit.
```

Allow running specific codemod(s)

---

poetry.lock
pyproject.toml

This is required to parse `.gitignore`, it was missed in #289.

fix: add pathspec to dependencies

---

django_codemod/visitors/base.py
tests/visitors/test_base.py

Similar to #306, codemodders might wrongly replace a kwargs with the same name as the imported function.
Changed the fix for attributes access to work with both cases. The previous fix was slowing down the codemodding process a lot, this version should provide a nice speed up.

fix: don't confuse kwargs with symbol to codemod

---

pyproject.toml

chore: use `version_toml` from PSR

---

pyproject.toml

Reverts browniebroke/django-codemod#319

chore: revert use `version_toml` from PSR

---

django_codemod/visitors/base.py
tests/visitors/test_base.py

When the old module appears as star import, it crashes with:
```
for import_alias in old_names:
TypeError: 'ImportStar' object is not iterable
```
We could probably handle renaming in this case, but let's be conservative and only avoid the crash for now.

fix: error with star import

---

django_codemod/visitors/base.py
django_codemod/visitors/core.py
django_codemod/visitors/decorators.py
django_codemod/visitors/urls.py
tests/visitors/test_base.py
tests/visitors/test_core.py

feat: handle rename when parent module is imported

---

pyproject.toml

Link from [Pypi package](https://pypi.org/project/django-codemod/) to [CHANGELOG](https://django-codemod.readthedocs.io/changelog.html) is broken. It returns 404 page.

docs: fix link to changelog on PyPI

---

commitlint.config.js
django_codemod/visitors/__init__.py
django_codemod/visitors/admin.py
django_codemod/visitors/exceptions.py
django_codemod/visitors/forms.py
django_codemod/visitors/template_context.py
docs/codemods.md
tests/visitors/test_admin.py
tests/visitors/test_exceptions.py
tests/visitors/test_forms.py
tests/visitors/test_template_context.py

Handle removed compatibility imports in 3.1
