django_codemod/codemods/django_40.py, tests/codemods/test_django_40.py
=> Fix bug for immediately invoked anonymous functions

django_codemod/visitors/base.py, tests/commands/test_django_40.py
=> Fix bug with trailing comma when removed import is the last one

.github/workflows/lint.yml, README.md, django_codemod/cli.py, django_codemod/commands/django_codemod.py, django_codemod/constants.py, django_codemod/visitors/__init__.py, django_codemod/visitors/admin.py, django_codemod/visitors/django_31.py, django_codemod/visitors/django_32.py, django_codemod/visitors/encoding.py, django_codemod/visitors/shortcuts.py, django_codemod/visitors/translations.py, django_codemod/visitors/urls.py, docs/codemods.rst, docs/usage.rst, tests/test_cli.py, tests/visitors/test_django_30.py, tests/visitors/test_django_40.py
=> Add new CLI option `--deprecated-in`

django_codemod/visitors/admin.py, tests/visitors/test_admin.py
=> Support fixing calls to base class has_add_permission in Admin Inline

setup.cfg
Version 5 and 6 have been released, let's see if it works with these
=> Update version restriction to rich<7

.github/workflows/lint.yml, .pre-commit-config.yaml, requirements.in, requirements.txt, setup.cfg
- Use black profile
- Run separately in CI
- Remove flake8-isort
- Add pre-commit hook
=> test: isort config improvements

.github/workflows/ci.yml
Fixes #214 
What this PR does : Merges ```test.yml```, ```lint.yml``` and ```commitlint.yml``` into a single file ```ci.yml```.
This is my first ever attempt at dealing with CI, so, do let me know if I need to correct something! Thanks :)
=> chore(ci): merge test, lint and commitlint workflows

django_codemod/visitors/__init__.py, django_codemod/visitors/postgres_fields.py, tests/visitors/test_postgres_fields.py
Ref: https://docs.djangoproject.com/en/3.1/releases/3.1/#jsonfield-for-all-supported-database-backends
=> feat: add a transformer for the new core JSONField in Django 3.1

README.md, docs/usage.md
=> docs: make recommended command less error prone

django_codemod/cli.py, django_codemod/path_utils.py, docs/usage.md, tests/test_cli.py, tests/test_path_utils.py
=> Ignore files according to .gitignore

README.md, docs/codemods.md, docs/index.md, docs/installation.md, docs/usage.md
=> Rework documentation

django_codemod/visitors/__init__.py, django_codemod/visitors/http.py, docs/codemods.md, tests/visitors/test_http.py
=> feat: add fixer for `django.utils.http.cookie_date`

.github/workflows/ci.yml, poetry.lock, pyproject.toml, tests/test_e2e.sh
=> fix: pin libCST to 0.3.13

django_codemod/visitors/base.py, tests/visitors/test_base.py
=> fix: bug with variable name same as import from outer scope

django_codemod/visitors/base.py, tests/visitors/test_base.py
=> fix: bug with attributes accessing

django_codemod/visitors/base.py
BaseRenameTransformer makes uses of the context scratch to keep track whether a symbol is called or just referenced.
This is quite complicated while libCST has built-in way to introspect that with parent node metadata:
https://libcst.readthedocs.io/en/latest/metadata.html#parent-node-metadata
=> refactor: replace custom context scratch by parent node metadata

django_codemod/visitors/base.py, tests/visitors/test_base.py
=> fix: rewrite parent module renaming logic

.github/workflows/ci.yml
It's now covered by pre-commit.ci
=> ci: remove lint job from CI

README.md
A long overdue note to point to @adamchainz project 😄
=> docs: add a note about django-upgrade in the readme

django_codemod/visitors/base.py, tests/visitors/test_base.py
Fixes https://github.com/browniebroke/django-codemod/issues/147
=> Avoid imports in try blocks

src/django_codemod/cli.py, tests/test_cli.py
=> fix: revert to libCST old parser

README.md
https://pypi.org/project/libcst
=> docs: update note regarding libCST Python versions support

pyproject.toml
=> feat(packaging): add tests to sdist

.readthedocs.yml, poetry.lock, pyproject.toml
Committed via https://github.com/asottile/all-repos
=> docs: replace docs extra by Poetry group

.github/workflows/ci.yml
Committed via https://github.com/asottile/all-repos
=> chore(deps): update snok/install-poetry action to v1.3.3

.flake8, .pre-commit-config.yaml, .sourcery.yaml, conftest.py, pyproject.toml, src/django_codemod/cli.py, src/django_codemod/path_utils.py, src/django_codemod/utils/calls.py, src/django_codemod/visitors/admin.py, src/django_codemod/visitors/base.py, src/django_codemod/visitors/crypto.py, src/django_codemod/visitors/exceptions.py, src/django_codemod/visitors/models.py, src/django_codemod/visitors/signals.py, src/django_codemod/visitors/urls.py, tests/test_cli.py, tests/visitors/test_models.py, tests/visitors/test_signals.py
Committed via https://github.com/asottile/all-repos
=> chore: switch linting to Ruff

.pre-commit-config.yaml, README.md, src/django_codemod/visitors/models.py, tests/visitors/test_admin.py, tests/visitors/test_base.py, tests/visitors/test_http.py, tests/visitors/test_models.py, tests/visitors/test_paginator.py, tests/visitors/test_postgres_fields.py, tests/visitors/test_signals.py, tests/visitors/test_template_tags.py, tests/visitors/test_timezone.py
Committed via https://github.com/asottile/all-repos
=> chore: switch to Ruff formatter
